### ISSUE TITLE
Apresentação para a Release01

### ISSUE THREAD

**Issue by joaovaladao** [fga-eps-mds/MDS-2020-2-G9#102]
### Descrição:
Devemos apresentar o produto que desenvolvemos até agora com uma apresentação comercial detalhada.

### Objetivos:

- [x] Introdução dos integrantes do grupo;
- [x] Informar a arquitetura utilizada na aplicação;
- [ ] Mostrar a aplicação funcionando, vídeo ou giff;
- [x] O problema que será solucionado, assim como o escopo do projeto;
- [x] Informar aquilo que desejamos atingir;

### Critérios de aceitação:

- [x] Definir a plataforma para criação da apresentação de slides;
- [x] Criar Slides relacionados aos objetivos listados;
- [x] Cada integrante deve ter ao menos m Slide para apresentar;
- [x] Tudo deve ser finalizado antes da entrega da Release01;

**Comment by vnsrz** [comment]
[Link dos slides para editar.](https://docs.google.com/presentation/d/1hG5Rirlpc9o5VA5o8gxl5AWCEoui_iAno6OKQUu4aIw/edit?usp=sharing)

**Comment by joaovaladao** [comment]
Ordem de apresentação:
João Victor -> Gabriel Avelino -> Christian -> Thiago -> Vinicius -> Ítalo

**Comment by joaovaladao** [comment]
Link vídeo: https://www.youtube.com/watch?v=55HeVJXf7L4&t=5s&ab_channel=Jo%C3%A3oVictorValad%C3%A3o
