### ISSUE TITLE
Review das Sprints

### ISSUE THREAD

**Issue by joaovaladao** [fga-eps-mds/MDS-2020-2-G9#105]
### Descrição:
Atualizar os reviews das Sprints antigas e implementar o Review da Sprint06

### Objetivos:

- [x] Inserir o gráfico do "Burndown Report" na Sprint05;
- [x] Criar a Review da Sprint06;
- [x] Criar o Preview da Sprint07;

### Critérios de aceitação:

- [x] Sprints antigas mais detalhadas;
- [x] 2 novos arquivos de Sprints;

**Comment by gabrielavelino** [comment]
Farei o planejamento da Sprint 07.
