### ISSUE TITLE
Documento de riscos

### ISSUE THREAD

**Issue by joaovaladao** [fga-eps-mds/MDS-2020-2-G9#108]
### Descrição:
Criar um plano de "Gerenciamento de Riscos" para a aplicação;

### Objetivos:

- [x] Identificar os possíveis riscos que podem acontecer no desenvolvimento do projeto;
- [x] Definir as prioridades de solução dos riscos;
- [x] Definir as contramedidas para as situações de risco;

### Critérios de aceitação:

- [x] O arquivo deve mostrar de forma clara quais ações devem ser tomadas em cada situação;

**Comment by gabrielavelino** [comment]
Começando a criação do documento de riscos.
