### ISSUE TITLE
Adicionar políticas à documentação

### ISSUE THREAD

**Issue by vnsrz** [fga-eps-mds/MDS-2020-2-G9#12]
### Descrição:
Adicionar políticas para padronizar as contribuições ao projeto.

### Objetivos:

- [x] Adicionar política de _commits_
- [x] Adicionar política de _issues_
- [x] Adicionar política de _pull requests_
- [x] Adicionar política de _branches_

### Critérios de aceitação:

- [x] Políticas devem ser seguidas por todos os membros

**Comment by joaovaladao** [comment]
Beleza, vamos fazer organizado a partir de agora
