### ISSUE TITLE
Abertura da documentação de metodologias!

### ISSUE THREAD

**Issue by gabrielavelino** [fga-eps-mds/MDS-2020-2-G9#14]
### Descrição:
 Criar um esboço do documento de metodologias e colocar no git!

### Objetivos:

- [x] Escolher as metodologias utilizadas;
- [x] Fazer a introdução explicando o por que de utilizá-las;
- [x] Definir as metodologias escolhidas;

### Critérios de aceitação:

- [x] Cumprir os objetivos definidos

**Comment by gabrielavelino** [comment]
As metodologias que utilizaremos serão a SCRUM e a Extreme Programming que serve como complemento ao SCRUM.

- SCRUM - https://www.desenvolvimentoagil.com.br/scrum/
- XP - https://www.treinaweb.com.br/blog/o-que-e-xp-extreme-programming/

**Comment by italofernandes13** [comment]
requisitos compridos
