### ISSUE TITLE
Atualizando a página configurações.

### ISSUE THREAD

**Issue by gabrielavelino** [fga-eps-mds/MDS-2020-2-G9#162]
### Descrição:
Adicionar e concluir as funções da pagina configurações do Med App.

### Objetivos:

- [x] Criação das funcionalidades.
- [x] Melhorar o visual da página.

### Critérios de aceitação:

- [x] Deixar o visual agradável para os clientes
- [x] adicionar botões de configurações do app

**Comment by joaovaladao** [comment]
Acredito que podemos implementar apenas um layout para a página, e deixamos as funcionalidades pra quem tiver animado nas férias.

**Comment by gabrielavelino** [comment]
Podemos usar os layouts e adicionar funcionalidades mais simples. 🍻
