### ISSUE TITLE
Assets

### ISSUE THREAD

**Issue by joaovaladao** [fga-eps-mds/MDS-2020-2-G9#175]
### Descrição:
No desenvolvimento web, o termo assets é utilizado para designar tudo o que complementa o conteúdo dos websites. Em outras palavras, assets são nossos recursos de folhas de estilo, scripts, fontes e imagens.

### Objetivos:

- [x] Definir uma nova logo;
- [x] Adicionar em arquivo tipo ícone (que seja aceito em Flutter);
- [ ] Definir a música da aplicação;
- [ ] Alterar as permissões e implementa-la no código;

### Critérios de aceitação:

- [ ] Lista de critérios

**Comment by gabrielavelino** [comment]
### Nova logo definida:

![medassistantBRANCO (1)](https://user-images.githubusercontent.com/48573662/117996720-c58ef700-b318-11eb-9430-461b2f72e0af.png)

**Comment by joaovaladao** [comment]
### Splash Screen foi redefinida com o novo ícone:
![WhatsApp Image 2021-05-13 at 10 33 27](https://user-images.githubusercontent.com/48729729/118133141-daca5b00-b3d6-11eb-9022-8c7c8fd24804.jpeg)

**Comment by joaovaladao** [comment]
Precisa de um ícone para ser chamado quando aparece uma nova notificação, pq esse ai fica muito pequeno. Além que o ícone aparece barco no fundo preto, e a imagem só da pílula não fica legal.
