### ISSUE TITLE
Todos estão preparados para apresentar?

### ISSUE THREAD

**Issue by joaovaladao** [fga-eps-mds/MDS-2020-2-G9#180]
### Descrição:
Vamos realizar a apresentação da realise02 na terça feira, e todos devem ter criado seu conteúdo e estarem preparados para apresentar.

### Objetivos:

- [x] Dar aquele último gás, e se preparar para a apresentação;
### Link dos Slides:
https://docs.google.com/presentation/d/1K8WMIs8du5ZG_DOLlOgxyaLajENa7MDy_4iJLWVqcOc/edit?usp=sharing

**Comment by joaovaladao** [comment]
João Victor Valadão: Introdução e arquitetura;
Ítalo Serra: Como foi a experiência de vcs (produtividade, métricas, quadro de conhecimento, velocity, análises);
Gabriel Avelino:  Mostrar o produto final de vcs!!! (show me product).

**Comment by gabrielavelino** [comment]
![image](https://user-images.githubusercontent.com/48573662/118578207-2035b200-b762-11eb-91aa-e1d7d2c40722.png)

Grupo se preparando para apresentação final!

**Comment by joaovaladao** [comment]
Link para a apresentação da Release 02:
https://www.youtube.com/watch?v=Suadjd3Xst0&ab_channel=Jo%C3%A3oVictorValad%C3%A3o
