### ISSUE TITLE
Feedback Sprint 04

### ISSUE THREAD

**Issue by youssef-md** [fga-eps-mds/MDS-2020-2-G9#24]
### Feedback Geral
Descrição geral sobre o feedack

**Práticas**
- [x] Quantidade de issues está de acordo com o esperado (pelo menos 1 issue por membro por sprint)
- [x] As issues estão bem escritas (alguém que não faz parte da equipe é capaz de entender e implementar a solução)
- [x] Os commits estão atômicos
- [x] Os commits estão bem comentados
- [x] O repositório está organizado
- [x] O ritmo do projeto está de acordo com o esperado
- [x] Estão comentando nas issues

**Sugestões de Melhorias**
- [x] Criar uma wiki para colocar todos os documentos(pode ser dentro desse mesmo repositório ao invés de usar o GitHub Pages. Segue [exemplo](https://github.com/fga-eps-mds/2018.1-Lacos-da-Alegria/wiki)). 
- [x] Padronização dos commits, sugiro o [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- [x] Rastreabilidade em geral, saber quem está com cada issue(assignes), comentar nas issues em que pé está a resolução da mesma a cada evolução, melhorar descrição, os objetivos e as tarefas.
- [x] Seguir as políticas que vocês definiram.
- [x] Calma em querer codar logo, vocês tem que ter ao menos bons documentos(visão, arquitetura, identidade visual, product backlog, etc) e um protótipo decente.
- [x] Inspirações para organização em geral e para documentos: [Kalkuli](https://fga-eps-mds.github.io/2018.2-Kalkuli/), [Pax](https://pax-app.github.io/Wiki/#/).
- [x] Criar label e adicinar nos nossos feedbacks.

**Comment by Bruno-Felix** [comment]
Vocês podem fechar a issue de feedback quando quiserem. O Gerenciamento dela, pós aberta, é por sua conta.
