### ISSUE TITLE
Alterar logo do projeto

### ISSUE THREAD

**Issue by vnsrz** [fga-eps-mds/MDS-2020-2-G9#39]
### Descrição:
Trocar a logo do MED assistant.

### Objetivos:

- [x] Tornar a logo mais legível para o usuário
- [x] Eliminar o fundo branco

### Critérios de aceitação:

- [ ] Grupo de acordo com a mudança

**Comment by vnsrz** [comment]
[Proposta de logo](https://imgur.com/42uBHLa)

**Comment by joaovaladao** [comment]
Ficou muito massa!!!

**Comment by vnsrz** [comment]
Logo alterada.
