### ISSUE TITLE
Arrumando o espaço de trabalho

### ISSUE THREAD

**Issue by joaovaladao** [fga-eps-mds/MDS-2020-2-G9#4]
-[] Baixem o Flutter em alguma plataforma disponível(VScode);
-[] Fazer o pull do arquivo base no repositório no GIT;

**Comment by chfleury** [comment]
ja tenho o ambiente pronto pro flutter, uso o vscode mesmo e o emulador do android studio. vou dar pull no repositorio

**Comment by gabrielavelino** [comment]
Vou preparar o ambiente e dar o pull em seguida também.
