### ISSUE TITLE
Criação do primeiro protótipo (Página Home)

### ISSUE THREAD

**Issue by joaovaladao** [fga-eps-mds/MDS-2020-2-G9#47]
### Descrição:
Criação da página inicial da aplicação

### Objetivos:

- [x] Definir uma plataforma;
- [x] Definir o layout da página;
- [ ] Criar o protótipo da página;

### Critérios de aceitação:
- [x] Arquivo com a imagem da página inicial;

**Comment by vnsrz** [comment]
Protótipo sendo criado no Adobe XD.

**Comment by vnsrz** [comment]
imagem adicionada.
