### ISSUE TITLE
#61 Revisar texto da Wiki

### ISSUE THREAD

**Issue by gabrielavelino** [fga-eps-mds/MDS-2020-2-G9#61]
### Descrição:
Corrigir erros gramaticais presentes na wiki do projeto.

### Objetivos:

- [x] Erros gramaticais corrigidos.

### Critérios de aceitação:

- [x] backlog
- [x] documentação metodologia
- [x] documentação comunicação
- [x] documentação de arquitetura
- [x] documentação de visão
- [x] road_map
- [x] termo de abertura

**Comment by gabrielavelino** [comment]
Todos os arquivos foram revisados.

**Comment by italofernandes13** [comment]
ajustando erros de ortografia
