### ISSUE TITLE
Criação de mais páginas no protótipo de alta fidelidade

### ISSUE THREAD

**Issue by vnsrz** [fga-eps-mds/MDS-2020-2-G9#67]
### Descrição:
Completar o protótipo de alta fidelidade com as páginas que faltam.

### Objetivos:

- [x] Criação da página Medicações
- [x] Criação da página Agendar
- [x] Prototipar a animação de mudança de páginas

### Critérios de aceitação:

- [x] Protótipo manter uma identidade visual concisa

**Comment by vnsrz** [comment]
[Barra de navegação remodelada e funcional.](https://imgur.com/GY340Nk)

**Comment by fowardshift** [comment]
[Preview do app.](https://xd.adobe.com/view/ec68f9dd-00e2-4b64-9466-1bada397e980-b93b/?fullscreen&hints=off)

**Comment by vnsrz** [comment]
[Preview do app.](https://xd.adobe.com/view/ec68f9dd-00e2-4b64-9466-1bada397e980-b93b/?fullscreen&hints=off)

**Comment by joaovaladao** [comment]
Vou te ajudar nessa ai

**Comment by joaovaladao** [comment]
Criei os templates básicos, agr o resto é a partir deles
