### ISSUE TITLE
Criando Templates e funções básicas

### ISSUE THREAD

**Issue by joaovaladao** [fga-eps-mds/MDS-2020-2-G9#7]
### Descrição:
Começar o desenvolvimento do app pelas páginas.

### Objetivos:

- [x] Decidir como serão as páginas da nossa aplicação;

### Critérios de aceitação:

- [ ] Definir a informação de cada páginas do app;

**Comment by vnsrz** [comment]
Até o momento foram definidas 3 páginas:
- home
- medicações
- agendar

**Comment by joaovaladao** [comment]
Home -> vai ter o nome do app na parte superior da página, um relógio centralizado, e uma barra de botões na parte inferior para irmos para as outras páginas;
Medicações -> será a página onde serão definidas os horários para cada medicação, e ela também é responsável por mostrar todas as medicações cadastradas;
Agendar -> permitirá ao usuário ver todos os dias em que as medicações foram tomadas corretamente;
