### ISSUE TITLE
Review sprint 5

### ISSUE THREAD

**Issue by italofernandes13** [fga-eps-mds/MDS-2020-2-G9#79]
### Descrição:
Criação do arquivo de Review da Sprint 5

### Objetivos:

- [x] Mostrar como os objetivos da Sprint foram atingidos;
- [x]  Mostrar aquilo que não conseguimos realizar;

### Critérios de aceitação:

- [x] Um arquivo .md

**Comment by joaovaladao** [comment]
Já foi finalizado o Milestone, pode criar o review da Sprint05
