### ISSUE TITLE
Arquivo para armazenar os protótipos

### ISSUE THREAD

**Issue by joaovaladao** [fga-eps-mds/MDS-2020-2-G9#84]
### Descrição:
Organizar as fotos dos protótipos em um único arquivo para facilitar o entendimento e organização do projeto.

### Objetivos:

- [x] Criar uma introdução explicando a função do documento;
- [x] Arrumar o repositório Miro onde estão localizados os protótipos de baixa fidelidade
- [x] Colocar as imagens dos protótipos de baixa fidelidade e um link para acessar o repositório;
- [x] Arrumar o repositório Adobe XD onde estão localizados os protótipos de alta fidelidade
- [x] Colocar as imagens dos protótipos de alta fidelidade e um link para acessar o repositório;

### Critérios de aceitação:

- [x] Um arquivo simples que atendam os objetivos acima;
- [x] Verificar se todas as fotos estão sendo carregadas normalmente;

**Comment by gabrielavelino** [comment]
Repositório Miro organizado.

**Comment by joaovaladao** [comment]
Valeu manin ❤️
