### ISSUE TITLE
Estudo da metodologia Scrum

### ISSUE THREAD

**Issue by fowardshift** [fga-eps-mds/MDS-2020-2-G9#9]
### Descrição:
Scrum é uma metodologia ágil para gestão e planejamento de projetos de software que deve ser estudada nessa semana por todos os integrantes.

### Objetivos:

- [x] Estudar a metodologia Scrum.

### Critérios de aceitação:

- [x] Todos os membros do grupo estarem aptos a executar o Scrum.

**Comment by fowardshift** [comment]
Site do [Desenvolvimento Agil](https://www.desenvolvimentoagil.com.br/scrum/) para referência.

**Comment by joaovaladao** [comment]
Vamos aplicar essa metodologia nas próximas Sprints
