### ISSUE TITLE
Arrumar bug do relógio de ponteiros

### ISSUE THREAD

**Issue by joaovaladao** [fga-eps-mds/MDS-2020-2-G9#91]
### Descrição:
O ponteiro marcador das horas funciona apenas no primeiro minuto, depois disso ele começa a agir aleatoriamente, enquanto o ponteiro dos minutos parece funcionar normalmente.

### Objetivos:

- [x] Descobrir o bug no relógio de ponteiros;(arquivo "clock_view.dart");
- [x] Solucionar o erro se possível, se não será substituído por um relógio digital;

### Critérios de aceitação:

- [x] Funcionamento adequado do arquivo "clock_view.dart"

**Comment by vnsrz** [comment]
Relógio digital funcional implementado.
